// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpX6V_I7fuBtjwTGfUhhbLT-mDgg4K6hg',
    appId: '1:965440046912:web:1c6e1459bc0465fa10dca5',
    messagingSenderId: '965440046912',
    projectId: 'watchy-ce045',
    authDomain: 'watchy-ce045.firebaseapp.com',
    storageBucket: 'watchy-ce045.firebasestorage.app',
    databaseURL: 'https://watchy-ce045-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDziUf5AizZpF0aVtIzmZFqNXDRyJ4eJ-M',
    appId: '1:965440046912:android:dabd179bef7b0ac610dca5',
    messagingSenderId: '965440046912',
    projectId: 'watchy-ce045',
    storageBucket: 'watchy-ce045.firebasestorage.app',
    databaseURL: 'https://watchy-ce045-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0NRyXUpHjrNHPh5oUInahxpQbdzzGP2g',
    appId: '1:965440046912:ios:f1b1c78f3982ef3e10dca5',
    messagingSenderId: '965440046912',
    projectId: 'watchy-ce045',
    storageBucket: 'watchy-ce045.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
    databaseURL: 'https://watchy-ce045-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0NRyXUpHjrNHPh5oUInahxpQbdzzGP2g',
    appId: '1:965440046912:ios:f1b1c78f3982ef3e10dca5',
    messagingSenderId: '965440046912',
    projectId: 'watchy-ce045',
    storageBucket: 'watchy-ce045.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
    databaseURL: 'https://watchy-ce045-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpX6V_I7fuBtjwTGfUhhbLT-mDgg4K6hg',
    appId: '1:965440046912:web:7eb655ddeedbb26b10dca5',
    messagingSenderId: '965440046912',
    projectId: 'watchy-ce045',
    authDomain: 'watchy-ce045.firebaseapp.com',
    storageBucket: 'watchy-ce045.firebasestorage.app',
    databaseURL: 'https://watchy-ce045-default-rtdb.firebaseio.com',
  );
}
