name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Flutter 🚀
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create .env file 📄
        run: echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" > .env

      - name: Install dependencies 📦
        run: flutter pub get

      - name: Build Web 🏗️
        run: flutter build web --release --base-href "/movieapp/"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
